# django_query_watch/constants.py

PACKAGE_NAME = "DJANGO-QUERY-WATCH"

LOG_PREFIX = f"[{PACKAGE_NAME}]"

SLOW_QUERY_LABEL = "SLOW QUERY"
DUPLICATE_LABEL = "DUPLICATE QUERY"
SUMMARY_LABEL = "SUMMARY"
WARNING_LABEL = "WARNING"

DEFAULT_SETTINGS = {
    "ENABLED": True,
    "SLOW_QUERY_THRESHOLD_MS": 200,
    "LOG_DUPLICATE_QUERIES": True,
    "LOG_QUERY_SUMMARY": True,
    "MAX_QUERY_PREVIEW_LENGTH": 500,
}
