[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "django-query-watch"
version = "1.0.0"
description = "Lightweight Django query performance monitoring and debugging toolkit"
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "Harini", email = "harinis05122001@gmail.com" }
]
keywords = [
    "django", "database", "performance", "debugging",
    "sql", "queries", "monitoring", "orm"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: Django",
    "Framework :: Django :: 4.0",
    "Framework :: Django :: 5.0",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Debuggers",
]
requires-python = ">=3.10"
dependencies = [
    "django>=4.0",
    "rich>=13.0",
]

[project.urls]
Homepage = "https://github.com/harinis05122001/django-query-watch.git"
Repository = "https://github.com/harinis05122001/django-query-watch.git"
Issues = "https://github.com/harinis05122001/django-query-watch.git/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["django_query_watch*"]